[package]
name = "shelly"
version = "0.1.0"
authors = ["Oscar Granada <oscar.andres.granada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
